### PR TITLE
add credo and lint checker

### PR DESCRIPTION
**Pull request by sigu**
Add code style checkers

### CODE REVIEW

**Comment by sigu** [comment]
THis is now ready for review

**Review by WanjikuMac — COMMENTED** [review]
@sigu does travis setup need postgresql?

**Comment by sigu** [comment]
Yes for it to run it needs to run tests which needs `repo` to activate the storage

image

**Comment by WanjikuMac** [comment]
Aaah good to know, everything else looks good to me.

**Pull request merged**
